### ISSUE TITLE
Quite a lot of build warning when installing to latest LTS of node.

### ISSUE THREAD

**Issue by develroo** [ukatama/nekoboard#18]
So installed Node 6.11.2 but installation  is not as clean as it should be.

`/usr/src/git/nekoboard# npm install
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated babel-preset-es2016@6.24.1: We're really excited that you're trying to use ES2016 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
npm WARN prefer global marked@0.3.6 should be installed with -g
`

I am not sure how active this project is but seems is diverging from the current node code base more and more.

**Comment by ukatama** [comment]
Several packages have been deprecated in the past year.
This repository is not maintained because I am building a new tool now.
However, it is easy to fix it, so I might fix it soon.

**Comment by ukatama** [comment]
Fix with #19

**Comment by develroo** [comment]
> Several packages have been deprecated in the past year.

Ahh figured as much. Node does seem to be a moving target sometimes. 

>This repository is not maintained because I am building a new tool now.

Oh? A new whiteboard like tool? If so that sounds interesting. The original reason I wanted to use nekoboard was to try it as as a inline Widget for Riot, the Matrix client. It allows you to embed any HTML/JS application into a channel. If that is a shared whiteboard means everyone in the channel can use it. 

Thanks for the fix I will see if I can build it now.

**Comment by ukatama** [comment]
Thank you for your interest. The problem have been fixed a while ago. (#19)

I do not know if the new product is what you want. Because it is like a tool combining nekochat and nekoboard, it is not just a white board.

I will fix if it is a serious Issue in nekoboard. I am glad if this will help you in your development.

**Comment by develroo** [comment]
> I do not know if the new product is what you want. Because it is like a tool combining nekochat and nekoboard, it is not just a white board.

Not sure what I really need per se. But I think nekobaord goes some way to it. If it is a combined chat/board/dice client then I am sure you will think about making the windows detachable in which case any or all of the components could be used.

> I will fix if it is a serious Issue in nekoboard. I am glad if this will help you in your development.

Thanks for that at least it builds now :) Most game board implementations deal with layers which can be shared or hidden as needed. If you are looking for inspiration I would consider that. 

Thanks for your efforts I will test it now see how well it works with Riot.
