### ISSUE TITLE
Buttons are too pale

### ISSUE THREAD

**Issue by MirrgieRiana** [ukatama/nekoboard#3]
下に図形挿入モードで並ぶ非選択の図形ボタンの色が薄すぎて、環境によっては見えないかもしれない

**Comment by ukatama** [comment]
対策どうしましょう

**Comment by MirrgieRiana** [comment]
次のような対策はどうか

- 鉛筆マークのように非選択を黒字・選択をショッキングピンク
- 非選択状態で「現在の選択状態に半透明の白膜を張り付けたボタン」・選択状態を今のまま
- 選択か否かにかかわらず同じアイコンで、オレンジの枠を付けるなどして選択していることを示す
