### ISSUE TITLE
List of pen configurations

### ISSUE THREAD

**Issue by MirrgieRiana** [ukatama/nekoboard#4]
挿入する図形の色・線の太さといった設定を、チャットルームの投稿欄みたいに複数保持したい

**Comment by ukatama** [comment]
描画スタイル設定ダイアログの中に付ける感じでどうでしょう？

**Comment by MirrgieRiana** [comment]
出来れば1クリックで描画色などの変更ができると良いと思います

**Comment by ukatama** [comment]
設定一式の履歴的なものはどうでしょう。

色選択ダイアログで選んだ色の履歴があるみたいな具合で

**Comment by MirrgieRiana** [comment]
異議なし
