### ISSUE TITLE
Too thin clickable area of line shapes

### ISSUE THREAD

**Issue by MirrgieRiana** [ukatama/nekoboard#5]
削除の当たり判定が小さく、細い線のみの図形の削除などが難しい

**Comment by ukatama** [comment]
DOMの仕様上難しいかも。
SVG要素のクリックイベントでやってるので

**Comment by ukatama** [comment]
- 当たり判定自体をなんとか大きくする
- マウスボタン押下＆ドラッグで削除できるようにする
